"""empty message

Revision ID: 12c0f685cde
Revises: 5a44cbcf5e2
Create Date: 2015-10-05 14:42:20.631202

"""

# revision identifiers, used by Alembic.
revision = '12c0f685cde'
down_revision = '5a44cbcf5e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_compoundsdb_barcode', table_name='compoundsdb')
    op.create_index(op.f('ix_compoundsdb_barcode'), 'compoundsdb', ['barcode'], unique=False)
    op.drop_index('ix_compoundsdb_concentration_range', table_name='compoundsdb')
    op.create_index(op.f('ix_compoundsdb_concentration_range'), 'compoundsdb', ['concentration_range'], unique=False)
    op.drop_index('ix_compoundsdb_starting_concentration', table_name='compoundsdb')
    op.create_index(op.f('ix_compoundsdb_starting_concentration'), 'compoundsdb', ['starting_concentration'], unique=False)
    op.drop_index('ix_compoundsdb_supplier', table_name='compoundsdb')
    op.create_index(op.f('ix_compoundsdb_supplier'), 'compoundsdb', ['supplier'], unique=False)
    op.drop_index('ix_compoundsdb_supplier_ref', table_name='compoundsdb')
    op.create_index(op.f('ix_compoundsdb_supplier_ref'), 'compoundsdb', ['supplier_ref'], unique=False)
    op.drop_index('ix_compoundsdb_well_ref', table_name='compoundsdb')
    op.create_index(op.f('ix_compoundsdb_well_ref'), 'compoundsdb', ['well_ref'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compoundsdb_well_ref'), table_name='compoundsdb')
    op.create_index('ix_compoundsdb_well_ref', 'compoundsdb', ['well_ref'], unique=1)
    op.drop_index(op.f('ix_compoundsdb_supplier_ref'), table_name='compoundsdb')
    op.create_index('ix_compoundsdb_supplier_ref', 'compoundsdb', ['supplier_ref'], unique=1)
    op.drop_index(op.f('ix_compoundsdb_supplier'), table_name='compoundsdb')
    op.create_index('ix_compoundsdb_supplier', 'compoundsdb', ['supplier'], unique=1)
    op.drop_index(op.f('ix_compoundsdb_starting_concentration'), table_name='compoundsdb')
    op.create_index('ix_compoundsdb_starting_concentration', 'compoundsdb', ['starting_concentration'], unique=1)
    op.drop_index(op.f('ix_compoundsdb_concentration_range'), table_name='compoundsdb')
    op.create_index('ix_compoundsdb_concentration_range', 'compoundsdb', ['concentration_range'], unique=1)
    op.drop_index(op.f('ix_compoundsdb_barcode'), table_name='compoundsdb')
    op.create_index('ix_compoundsdb_barcode', 'compoundsdb', ['barcode'], unique=1)
    ### end Alembic commands ###
