"""empty message

Revision ID: 5a44cbcf5e2
Revises: None
Create Date: 2015-10-05 13:32:45.239155

"""

# revision identifiers, used by Alembic.
revision = '5a44cbcf5e2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compoundsdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formatted_batch_id', sa.String(length=64), nullable=True),
    sa.Column('supplier', sa.String(length=64), nullable=True),
    sa.Column('supplier_ref', sa.String(length=64), nullable=True),
    sa.Column('well_ref', sa.String(length=64), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('starting_concentration', sa.String(length=64), nullable=True),
    sa.Column('concentration_range', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compoundsdb_barcode'), 'compoundsdb', ['barcode'], unique=True)
    op.create_index(op.f('ix_compoundsdb_concentration_range'), 'compoundsdb', ['concentration_range'], unique=True)
    op.create_index(op.f('ix_compoundsdb_formatted_batch_id'), 'compoundsdb', ['formatted_batch_id'], unique=True)
    op.create_index(op.f('ix_compoundsdb_starting_concentration'), 'compoundsdb', ['starting_concentration'], unique=True)
    op.create_index(op.f('ix_compoundsdb_supplier'), 'compoundsdb', ['supplier'], unique=True)
    op.create_index(op.f('ix_compoundsdb_supplier_ref'), 'compoundsdb', ['supplier_ref'], unique=True)
    op.create_index(op.f('ix_compoundsdb_well_ref'), 'compoundsdb', ['well_ref'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compoundsdb_well_ref'), table_name='compoundsdb')
    op.drop_index(op.f('ix_compoundsdb_supplier_ref'), table_name='compoundsdb')
    op.drop_index(op.f('ix_compoundsdb_supplier'), table_name='compoundsdb')
    op.drop_index(op.f('ix_compoundsdb_starting_concentration'), table_name='compoundsdb')
    op.drop_index(op.f('ix_compoundsdb_formatted_batch_id'), table_name='compoundsdb')
    op.drop_index(op.f('ix_compoundsdb_concentration_range'), table_name='compoundsdb')
    op.drop_index(op.f('ix_compoundsdb_barcode'), table_name='compoundsdb')
    op.drop_table('compoundsdb')
    ### end Alembic commands ###
